version: '3.7'

services:
  mongo:
    restart: always
    image: mongo
    container_name: foodie-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foodie
      - MONGO_INITDB_ROOT_PASSWORD=foodie
      - MONGO_INITDB_DATABASE=foodie
    ports:
      - 27018:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: mongod --auth

  postgres:
    image: postgres
    container_name: foodie-postgres
    environment:
      - POSTGRES_PASSWORD=foodie
      - POSTGRES_USER=foodie
      - POSTGRES_DB=foodie
    ports:
      - 5501:5432

  foodie:
    build: .
    restart: always
    container_name: foodie
    ports:
      - 8182:8080
    working_dir: /opt/app
    depends_on:
      - postgres